test_cases = [
    # 1-5: حالات طبيعية متنوعة
    {
        "name": "شخص طبيعي (شاب)",
        "category": "normal",
        "vitals": {
            "heart_rate": 72,
            "spo2": 98,
            "temperature": 36.7,
            "systolic_bp": 115,
            "diastolic_bp": 75,
        },
        "expected": False,
        "expected_severity": "Normal",
    },
    {
        "name": "شخص طبيعي (متوسط العمر)",
        "category": "normal",
        "vitals": {
            "heart_rate": 75,
            "spo2": 97,
            "temperature": 36.8,
            "systolic_bp": 118,
            "diastolic_bp": 78,
        },
        "expected": False,
        "expected_severity": "Normal",
    },
    {
        "name": "رياضي (معدل نبض منخفض)",
        "category": "normal_special",
        "vitals": {
            "heart_rate": 45,
            "spo2": 99,
            "temperature": 36.5,
            "systolic_bp": 110,
            "diastolic_bp": 70,
        },
        "expected": False,
        "expected_severity": "Normal",
    },
    {
        "name": "امرأة حامل (طبيعية)",
        "category": "normal_special",
        "vitals": {
            "heart_rate": 85,
            "spo2": 98,
            "temperature": 37.0,
            "systolic_bp": 115,
            "diastolic_bp": 75,
        },
        "expected": False,
        "expected_severity": "Normal",
    },
    {
        "name": "كبير السن (طبيعي مثالي)",
        "category": "normal_special",
        "vitals": {
            "heart_rate": 68,
            "spo2": 96,
            "temperature": 36.6,
            "systolic_bp": 125,
            "diastolic_bp": 78,
        },
        "expected": False,
        "expected_severity": "Normal",
    },
    # 6-10: حالات حدية (خفيفة)
    {
        "name": "ارتفاع ضغط خفيف (مرحلة أولى)",
        "category": "borderline",
        "vitals": {
            "heart_rate": 78,
            "spo2": 97,
            "temperature": 36.8,
            "systolic_bp": 135,
            "diastolic_bp": 88,
        },
        "expected": True,
        "expected_severity": "Mild",
    },
    {
        "name": "كبير السن مع ارتفاع ضغط طبيعي للعمر",
        "category": "borderline",
        "vitals": {
            "heart_rate": 68,
            "spo2": 96,
            "temperature": 36.6,
            "systolic_bp": 135,
            "diastolic_bp": 85,
        },
        "expected": True,
        "expected_severity": "Mild",
    },
    {
        "name": "ارتفاع ضغط حدي",
        "category": "borderline",
        "vitals": {
            "heart_rate": 80,
            "spo2": 96,
            "temperature": 37.0,
            "systolic_bp": 140,
            "diastolic_bp": 90,
        },
        "expected": True,
        "expected_severity": "Mild",
    },
    {
        "name": "انخفاض أكسجين خفيف",
        "category": "borderline",
        "vitals": {
            "heart_rate": 85,
            "spo2": 94,
            "temperature": 36.9,
            "systolic_bp": 120,
            "diastolic_bp": 80,
        },
        "expected": True,
        "expected_severity": "Mild",
    },
    {
        "name": "تسارع قلب خفيف",
        "category": "borderline",
        "vitals": {
            "heart_rate": 105,
            "spo2": 98,
            "temperature": 37.1,
            "systolic_bp": 125,
            "diastolic_bp": 82,
        },
        "expected": True,
        "expected_severity": "Mild",
    },
    # 11-15: حالات متوسطة الشدة
    {
        "name": "ارتفاع ضغط متوسط (مرحلة ثانية)",
        "category": "moderate",
        "vitals": {
            "heart_rate": 85,
            "spo2": 96,
            "temperature": 37.0,
            "systolic_bp": 155,
            "diastolic_bp": 95,
        },
        "expected": True,
        "expected_severity": "Moderate",
    },
    {
        "name": "انخفاض أكسجين متوسط",
        "category": "moderate",
        "vitals": {
            "heart_rate": 95,
            "spo2": 90,
            "temperature": 37.0,
            "systolic_bp": 118,
            "diastolic_bp": 78,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "تسارع قلب متوسط",
        "category": "moderate",
        "vitals": {
            "heart_rate": 120,
            "spo2": 97,
            "temperature": 37.2,
            "systolic_bp": 130,
            "diastolic_bp": 85,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "حمى متوسطة",
        "category": "moderate",
        "vitals": {
            "heart_rate": 100,
            "spo2": 96,
            "temperature": 38.5,
            "systolic_bp": 125,
            "diastolic_bp": 82,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "انخفاض ضغط خفيف",
        "category": "moderate",
        "vitals": {
            "heart_rate": 95,
            "spo2": 97,
            "temperature": 36.8,
            "systolic_bp": 95,
            "diastolic_bp": 60,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    # 16-20: حالات حرجة
    {
        "name": "ارتفاع ضغط حاد",
        "category": "critical",
        "vitals": {
            "heart_rate": 110,
            "spo2": 95,
            "temperature": 37.3,
            "systolic_bp": 180,
            "diastolic_bp": 110,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "نقص أكسجين حاد",
        "category": "critical",
        "vitals": {
            "heart_rate": 120,
            "spo2": 85,
            "temperature": 37.2,
            "systolic_bp": 100,
            "diastolic_bp": 65,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "تسارع قلب حاد",
        "category": "critical",
        "vitals": {
            "heart_rate": 150,
            "spo2": 95,
            "temperature": 37.5,
            "systolic_bp": 140,
            "diastolic_bp": 90,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "حمى عالية",
        "category": "critical",
        "vitals": {
            "heart_rate": 130,
            "spo2": 96,
            "temperature": 39.5,
            "systolic_bp": 130,
            "diastolic_bp": 85,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "انخفاض ضغط حاد",
        "category": "critical",
        "vitals": {
            "heart_rate": 110,
            "spo2": 94,
            "temperature": 36.5,
            "systolic_bp": 80,
            "diastolic_bp": 50,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    # 21-25: حالات متعددة الأعراض
    {
        "name": "عدوى تنفسية (حمى + نقص أكسجين)",
        "category": "multi_symptom",
        "vitals": {
            "heart_rate": 110,
            "spo2": 92,
            "temperature": 38.8,
            "systolic_bp": 115,
            "diastolic_bp": 75,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "أزمة قلبية (ألم صدر + تسارع قلب)",
        "category": "multi_symptom",
        "vitals": {
            "heart_rate": 140,
            "spo2": 95,
            "temperature": 37.0,
            "systolic_bp": 160,
            "diastolic_bp": 100,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "جفاف شديد (انخفاض ضغط + تسارع قلب)",
        "category": "multi_symptom",
        "vitals": {
            "heart_rate": 125,
            "spo2": 96,
            "temperature": 37.8,
            "systolic_bp": 85,
            "diastolic_bp": 55,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "فشل تنفسي (نقص أكسجين + تسارع قلب)",
        "category": "multi_symptom",
        "vitals": {
            "heart_rate": 130,
            "spo2": 88,
            "temperature": 37.2,
            "systolic_bp": 145,
            "diastolic_bp": 92,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "صدمة إنتانية (انخفاض ضغط + حمى)",
        "category": "multi_symptom",
        "vitals": {
            "heart_rate": 135,
            "spo2": 93,
            "temperature": 39.2,
            "systolic_bp": 75,
            "diastolic_bp": 45,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    # 26-30: حالات خاصة ومعقدة
    {
        "name": "رياضي مع إرهاق",
        "category": "special",
        "vitals": {
            "heart_rate": 55,
            "spo2": 98,
            "temperature": 37.8,
            "systolic_bp": 105,
            "diastolic_bp": 65,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "حامل مع ارتفاع ضغط",
        "category": "special",
        "vitals": {
            "heart_rate": 95,
            "spo2": 97,
            "temperature": 37.1,
            "systolic_bp": 145,
            "diastolic_bp": 92,
        },
        "expected": True,
        "expected_severity": "Moderate",
    },
    {
        "name": "مريض قلب مزمن",
        "category": "special",
        "vitals": {
            "heart_rate": 88,
            "spo2": 94,
            "temperature": 36.9,
            "systolic_bp": 150,
            "diastolic_bp": 95,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "مريض رئة مزمن",
        "category": "special",
        "vitals": {
            "heart_rate": 92,
            "spo2": 91,
            "temperature": 37.0,
            "systolic_bp": 125,
            "diastolic_bp": 80,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "مريض سكري مع انخفاض ضغط",
        "category": "special",
        "vitals": {
            "heart_rate": 105,
            "spo2": 96,
            "temperature": 36.7,
            "systolic_bp": 90,
            "diastolic_bp": 58,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    # 31-35: حالات طارئة
    {
        "name": "سكتة دماغية محتملة",
        "category": "emergency",
        "vitals": {
            "heart_rate": 115,
            "spo2": 95,
            "temperature": 37.0,
            "systolic_bp": 190,
            "diastolic_bp": 120,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "انسداد رئوي حاد",
        "category": "emergency",
        "vitals": {
            "heart_rate": 145,
            "spo2": 82,
            "temperature": 37.1,
            "systolic_bp": 90,
            "diastolic_bp": 60,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "نوبة قلبية",
        "category": "emergency",
        "vitals": {
            "heart_rate": 155,
            "spo2": 90,
            "temperature": 37.2,
            "systolic_bp": 85,
            "diastolic_bp": 55,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "صدمة تحسسية",
        "category": "emergency",
        "vitals": {
            "heart_rate": 135,
            "spo2": 88,
            "temperature": 36.8,
            "systolic_bp": 70,
            "diastolic_bp": 45,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "نزيف حاد",
        "category": "emergency",
        "vitals": {
            "heart_rate": 140,
            "spo2": 93,
            "temperature": 36.5,
            "systolic_bp": 75,
            "diastolic_bp": 50,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    # 36-40: حالات مزمنة
    {
        "name": "فشل كلوي مزمن",
        "category": "chronic",
        "vitals": {
            "heart_rate": 90,
            "spo2": 96,
            "temperature": 37.0,
            "systolic_bp": 160,
            "diastolic_bp": 95,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "قصور قلب احتقاني",
        "category": "chronic",
        "vitals": {
            "heart_rate": 110,
            "spo2": 93,
            "temperature": 37.1,
            "systolic_bp": 145,
            "diastolic_bp": 90,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "مرض رئوي انسدادي مزمن",
        "category": "chronic",
        "vitals": {
            "heart_rate": 95,
            "spo2": 89,
            "temperature": 36.9,
            "systolic_bp": 130,
            "diastolic_bp": 85,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "ارتفاع ضغط مزمن غير مسيطر عليه",
        "category": "chronic",
        "vitals": {
            "heart_rate": 85,
            "spo2": 97,
            "temperature": 36.8,
            "systolic_bp": 170,
            "diastolic_bp": 105,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "قصور في الغدة الدرقية",
        "category": "chronic",
        "vitals": {
            "heart_rate": 55,
            "spo2": 97,
            "temperature": 35.8,
            "systolic_bp": 110,
            "diastolic_bp": 70,
        },
        "expected": True,
        "expected_severity": "Mild",
    },
    # 41-45: حالات متنوعة
    {
        "name": "شاب مع ضغط منخفض",
        "category": "normal_special",
        "vitals": {
            "heart_rate": 75,
            "spo2": 98,
            "temperature": 36.6,
            "systolic_bp": 100,
            "diastolic_bp": 65,
        },
        "expected": False,
        "expected_severity": "Normal",
    },
    {
        "name": "طفل (5 سنوات)",
        "category": "normal_special",
        "vitals": {
            "heart_rate": 95,
            "spo2": 99,
            "temperature": 37.0,
            "systolic_bp": 95,
            "diastolic_bp": 60,
        },
        "expected": False,
        "expected_severity": "Normal",
    },
    {
        "name": "ممارس رياضة عنيفة",
        "category": "normal_special",
        "vitals": {
            "heart_rate": 135,
            "spo2": 99,
            "temperature": 37.2,
            "systolic_bp": 140,
            "diastolic_bp": 85,
        },
        "expected": True,
        "expected_severity": "Mild",
    },
    {
        "name": "تسمم غذائي",
        "category": "multi_symptom",
        "vitals": {
            "heart_rate": 105,
            "spo2": 97,
            "temperature": 38.0,
            "systolic_bp": 100,
            "diastolic_bp": 65,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "التهاب رئوي",
        "category": "multi_symptom",
        "vitals": {
            "heart_rate": 115,
            "spo2": 91,
            "temperature": 39.0,
            "systolic_bp": 110,
            "diastolic_bp": 70,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    # 46-50: حالات إضافية
    {
        "name": "اضطراب نظم القلب",
        "category": "critical",
        "vitals": {
            "heart_rate": 165,
            "spo2": 96,
            "temperature": 37.0,
            "systolic_bp": 120,
            "diastolic_bp": 80,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "انخفاض شديد في حرارة الجسم",
        "category": "critical",
        "vitals": {
            "heart_rate": 50,
            "spo2": 96,
            "temperature": 35.0,
            "systolic_bp": 90,
            "diastolic_bp": 60,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "ارتفاع شديد في حرارة الجسم",
        "category": "critical",
        "vitals": {
            "heart_rate": 145,
            "spo2": 95,
            "temperature": 41.0,
            "systolic_bp": 110,
            "diastolic_bp": 70,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "انسداد في الشريان التاجي",
        "category": "emergency",
        "vitals": {
            "heart_rate": 130,
            "spo2": 94,
            "temperature": 37.3,
            "systolic_bp": 150,
            "diastolic_bp": 95,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
    {
        "name": "فشل كبدي",
        "category": "chronic",
        "vitals": {
            "heart_rate": 100,
            "spo2": 95,
            "temperature": 37.5,
            "systolic_bp": 105,
            "diastolic_bp": 65,
        },
        "expected": True,
        "expected_severity": "Critical",
    },
]